const MESSAGE_IDS = {
    ADD_NEW_NETWORK_PLAYER: "AnP",
    COLLECT: "C",
    DESTROY_BLOCK: "DB",
    GET_PLAYER_DATA: "GPd",
    GET_WORLD_COMPRESSED: "GWC",
    LEAVE_WORLD: "LW",
    NEW_COLLECTABLE: "nCo",
    OTHER_OWNER_IP: "OoIP",
    PLAYER_LEFT: "PL",
    REMOVE_COLLECTABLE: "RC",
    REMOVE_ITEM_FROM_INVENTORY: "RIi",
    SET_BLOCK: "SB",
    SET_BLOCK_BACKGROUND: "SBB",
    SET_BLOCK_WATER: "SBW",
    SET_SEED: "SS",
    WORLD_CHAT_MESSAGE: "WCM"
};

module.exports = MESSAGE_IDS;